### ISSUE TITLE
SSRI code list is in scientific notation and breaks the codes

### ISSUE THREAD

**Issue by prhc0612** [aim-rsf/drug-lists#12]
Hello my friend,
The first column in SSRIs_CPRD_AURUM.csv is meant to have the (snomed?) code, however it is being stored in scientific notation which provides the wrong code when expanded.

This is often caused when people make the mistake of using Microsoft Excel, my advise is to never use Excel for anything data related, it is a terrible tool!

Please can you re-upload with the correct codes. If Excel is being used, ensure that column is treated as text and not numbers before you save. Otherwise using any plain text editor (Notepad++, VIM, EMACs, Visual Studio Code or Notepad on windows) will save things correctly.

thank you muchly.

**Comment by BatoolMM** [comment]
Thank you @prhc0612 - we'll look into it. You mean the 1st column here: 
```
DRUG_CODE_ID,DESCRIPTION,BNF1,BNF2,BNF3,ATC,DATABASE
5.10404E+15,Seroxat Cr M/R tablets 12.5 mg    ,,,,,CPRD_AURUM
3.19984E+15,Paxoran Tablets 10 mg    ,,,,,CPRD_AURUM
3.20004E+15,Paxoran Tablets 40 mg    ,,,,,CPRD_AURUM
```
I am not sure that Microsoft Excel was used in handling the data at all but will look into it.

**Comment by prhc0612** [comment]
> Thank you @prhc0612 - we'll look into it. You mean the 1st column here:
> 
> ```
> DRUG_CODE_ID,DESCRIPTION,BNF1,BNF2,BNF3,ATC,DATABASE
> 5.10404E+15,Seroxat Cr M/R tablets 12.5 mg    ,,,,,CPRD_AURUM
> 3.19984E+15,Paxoran Tablets 10 mg    ,,,,,CPRD_AURUM
> 3.20004E+15,Paxoran Tablets 40 mg    ,,,,,CPRD_AURUM
> ```
> 
> I am not sure that Microsoft Excel was used in handling the data at all but will look into it.

Hi @BatoolMM ,
Yes the DRUG_CODE_ID is the one. Many thanks for your quick response.

**Comment by BatoolMM** [comment]
I have submitted a new PR #13 - @Rainiefantasy will review it later. Thank you for flagging this again @prhc0612!
